### ISSUE TITLE
Server Side Encryption

### ISSUE THREAD

**Issue by nonlefthanded** [happycog/VMG-S3-Direct-Upload#2]
Hi,

Is there a provision / option for server-side encryption on this plugin? 

It looks like I need to submit the "x-amz-server-side-encryption" header, but I'm not seeing a way to do that. Am I missing something?

Thanks for the code, and the help,
CJ

**Comment by khaliqgant** [comment]
Hi!, so sorry, I am just now seeing this. I will take a look at get back to you.

**Comment by khaliqgant** [comment]
Apologies on this again, not going to be able to get to it.
